/// Types for text input handling, vim mode, and command queuing.
///
/// Migrated from the OpenClaude TypeScript `types/textInputTypes.ts`.
library;

import 'package:neom_claw/domain/models/ids.dart';
import 'package:neom_claw/domain/models/message.dart';
import 'package:neom_claw/domain/models/permissions.dart';

// ---------------------------------------------------------------------------
// Message origin
// ---------------------------------------------------------------------------

/// Provenance of a queued command or user message.
///
/// Tracks where a message originated so the transcript can record origin
/// structurally rather than relying on XML tags in content.
enum MessageOrigin {
  /// Typed by the user at the keyboard.
  human,

  /// Received from a remote bridge (mobile / web client).
  bridge,

  /// Generated by a cron / scheduled task.
  cron,

  /// System-generated (proactive tick, resource update, etc.).
  system,
}

// ---------------------------------------------------------------------------
// Inline ghost text
// ---------------------------------------------------------------------------

/// Inline ghost text shown during mid-input command autocomplete.
class InlineGhostText {
  /// The ghost text to display (e.g. "mit" for /commit).
  final String text;

  /// The full command name (e.g. "commit").
  final String fullCommand;

  /// Position in the input where the ghost text should appear.
  final int insertPosition;

  /// Creates an [InlineGhostText].
  const InlineGhostText({
    required this.text,
    required this.fullCommand,
    required this.insertPosition,
  });
}

// ---------------------------------------------------------------------------
// Vim mode
// ---------------------------------------------------------------------------

/// Vim editor modes.
enum VimMode {
  /// Insert mode — keystrokes produce text.
  insert,

  /// Normal mode — keystrokes are interpreted as commands.
  normal;

  /// Display label matching the original TypeScript union values.
  String get label => switch (this) {
    VimMode.insert => 'INSERT',
    VimMode.normal => 'NORMAL',
  };
}

// ---------------------------------------------------------------------------
// Input state
// ---------------------------------------------------------------------------

/// Paste buffer state.
class PasteState {
  /// Accumulated paste chunks.
  final List<String> chunks;

  /// Creates a [PasteState].
  const PasteState({this.chunks = const []});
}

/// Common properties shared by all input state variants.
class BaseInputState {
  /// Rendered (possibly wrapped) value of the input.
  final String renderedValue;

  /// Character offset of the cursor within the full text.
  final int offset;

  /// Cursor line (0-indexed) within the rendered text, accounting for wrapping.
  final int cursorLine;

  /// Cursor column (display-width) within the current line.
  final int cursorColumn;

  /// Character offset where the viewport starts (0 when no windowing).
  final int viewportCharOffset;

  /// Character offset where the viewport ends (text.length when no windowing).
  final int viewportCharEnd;

  /// Whether a paste operation is in progress.
  final bool isPasting;

  /// Active paste buffer state, if any.
  final PasteState? pasteState;

  /// Creates a [BaseInputState].
  const BaseInputState({
    required this.renderedValue,
    required this.offset,
    required this.cursorLine,
    required this.cursorColumn,
    required this.viewportCharOffset,
    required this.viewportCharEnd,
    this.isPasting = false,
    this.pasteState,
  });
}

/// State for a standard (non-vim) text input.
typedef TextInputState = BaseInputState;

/// State for a vim-mode text input, extending [BaseInputState] with
/// the current [VimMode].
class VimInputState extends BaseInputState {
  /// The current vim mode.
  final VimMode mode;

  /// Creates a [VimInputState].
  const VimInputState({
    required super.renderedValue,
    required super.offset,
    required super.cursorLine,
    required super.cursorColumn,
    required super.viewportCharOffset,
    required super.viewportCharEnd,
    super.isPasting,
    super.pasteState,
    this.mode = VimMode.insert,
  });

  /// Returns a copy with the given [mode].
  VimInputState copyWithMode(VimMode mode) => VimInputState(
    renderedValue: renderedValue,
    offset: offset,
    cursorLine: cursorLine,
    cursorColumn: cursorColumn,
    viewportCharOffset: viewportCharOffset,
    viewportCharEnd: viewportCharEnd,
    isPasting: isPasting,
    pasteState: pasteState,
    mode: mode,
  );
}

// ---------------------------------------------------------------------------
// Prompt input mode
// ---------------------------------------------------------------------------

/// Input modes for the prompt.
enum PromptInputMode {
  /// Standard conversational prompt.
  prompt,

  /// Bash / shell command input.
  bash,

  /// An orphaned permission prompt waiting for resolution.
  orphanedPermission,

  /// A background-task notification.
  taskNotification;

  /// Whether this mode supports direct text editing.
  bool get isEditable => switch (this) {
    PromptInputMode.prompt || PromptInputMode.bash => true,
    _ => false,
  };
}

// ---------------------------------------------------------------------------
// Queue priority
// ---------------------------------------------------------------------------

/// Priority levels for queued commands.
///
/// - [now]   -- Interrupt and send immediately (aborts in-flight tool call).
/// - [next]  -- Send after the current tool call finishes, before the next
///              API round-trip.
/// - [later] -- Send after the current turn completes as a new query.
enum QueuePriority {
  /// Interrupt and send immediately.
  now,

  /// Send between tool-call result and next API round-trip.
  next,

  /// Wait for the current turn to finish, then process.
  later,
}

// ---------------------------------------------------------------------------
// Orphaned permission
// ---------------------------------------------------------------------------

/// A permission result left over from a previous turn that still needs
/// to be resolved.
class OrphanedPermission {
  /// The permission decision.
  final PermissionResult permissionResult;

  /// The assistant message that triggered the permission request.
  final Message assistantMessage;

  /// Creates an [OrphanedPermission].
  const OrphanedPermission({
    required this.permissionResult,
    required this.assistantMessage,
  });
}

// ---------------------------------------------------------------------------
// Pasted content helpers
// ---------------------------------------------------------------------------

/// Represents pasted content (text or image) attached to a queued command.
class InputPastedContent {
  /// Unique identifier for this pasted item.
  final int id;

  /// Content type: `'text'` or `'image'`.
  final String type;

  /// The raw content string (plain text or base64-encoded image data).
  final String content;

  /// Creates an [InputPastedContent].
  const InputPastedContent({
    required this.id,
    required this.type,
    required this.content,
  });

  /// Whether this is a valid (non-empty) image paste.
  bool get isValidImage => type == 'image' && content.isNotEmpty;
}

// ---------------------------------------------------------------------------
// Queued command
// ---------------------------------------------------------------------------

/// A command queued for deferred execution when the model is busy.
class QueuedCommand {
  /// The prompt value — either a plain string or structured content blocks.
  final Object /* String | List<ContentBlock> */ value;

  /// The input mode under which this command was submitted.
  final PromptInputMode mode;

  /// Drain priority. Defaults to the priority implied by [mode] when
  /// enqueued.
  final QueuePriority? priority;

  /// Optional unique identifier for this command.
  final String? uuid;

  /// An orphaned permission still pending resolution.
  final OrphanedPermission? orphanedPermission;

  /// Raw pasted contents including images. Images are resized at
  /// execution time. Keyed by paste index.
  final Map<int, InputPastedContent>? pastedContents;

  /// The input string before `[Pasted text #N]` placeholders were
  /// expanded. Used for keyword detection so pasted content containing
  /// the keyword does not trigger unintended behaviour. Falls back to
  /// [value] when unset.
  final String? preExpansionValue;

  /// When `true`, the input is treated as plain text even if it starts
  /// with `/`. Used for remotely-received messages that should not
  /// trigger local slash commands.
  final bool skipSlashCommands;

  /// When `true`, slash commands are dispatched but filtered through a
  /// bridge-safety check. Unsafe commands return a helpful error instead
  /// of executing.
  final bool bridgeOrigin;

  /// When `true`, the resulting message gets `isMeta: true` -- hidden in
  /// the transcript UI but visible to the model.
  final bool isMeta;

  /// Provenance of this command (e.g. human keyboard, bridge, cron).
  final MessageOrigin? origin;

  /// Workload tag threaded through to billing attribution.
  final String? workload;

  /// Agent that should receive this notification. `null` = main thread.
  final AgentId? agentId;

  /// Creates a [QueuedCommand].
  const QueuedCommand({
    required this.value,
    required this.mode,
    this.priority,
    this.uuid,
    this.orphanedPermission,
    this.pastedContents,
    this.preExpansionValue,
    this.skipSlashCommands = false,
    this.bridgeOrigin = false,
    this.isMeta = false,
    this.origin,
    this.workload,
    this.agentId,
  });
}

// ---------------------------------------------------------------------------
// Utility functions
// ---------------------------------------------------------------------------

/// Returns `true` when [content] represents a non-empty image paste.
bool isValidImagePaste(InputPastedContent content) => content.isValidImage;

/// Extract image paste IDs from a [QueuedCommand]'s [pastedContents].
///
/// Returns `null` when there are no valid image pastes.
List<int>? getImagePasteIds(Map<int, InputPastedContent>? pastedContents) {
  if (pastedContents == null) return null;
  final ids =
      pastedContents.values
          .where((c) => c.isValidImage)
          .map((c) => c.id)
          .toList();
  return ids.isNotEmpty ? ids : null;
}
